services:
  # --- MQTT Broker ---
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "1883"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # --- InfluxDB 2.x ---
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=greenhouse
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    restart: unless-stopped

  # --- Mock Sensor Data Generator ---
  mock_sensors:
    build: ./mock_data
    container_name: mock_sensors
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    restart: unless-stopped

  # --- Data Processor (MQTT → InfluxDB) ---
  data_processor:
    build: ./data_processor
    container_name: data_processor
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto: 
        condition: service_healthy
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    restart: unless-stopped

  # --- Control Loop ---
  control_loop:
    build: ./control_loop
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=greenhouse
      - INFLUXDB_BUCKET=sensor_data
    restart: unless-stopped
