apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: greenhouse
      defaultBucket: sensor_data
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
